# To set up a development environment using conda, run:
#
#   conda env create -f environment.yml
#   conda activate geopy

# '''
# Environment created for the book "Geospatial analytics with Python"
# at LocatePress editorial
# It makes available the python libraries needed for the geospatial processing
# during the book's chapters.
#
# Author: Bryan R. Vallejo @BryanRVallejo
# '''
name: geopy
channels:
  - conda-forge
dependencies:
  - python==3.8
  - geopandas
  - shapely>=1.6.4
  - osmnx
  - networkx
  - matplotlib==3.4.3
  # - cython>=0.28.5
  # - numpy>=1.18

  # - geos>=3.7.2
  # - pyshp>=2.1
  # - pyproj>=3.0.0
  # # PROJ is still required for now
  # - proj>=8
  # # The testing label has the proper version of freetype included
  # # - conda-forge/label/testing::matplotlib-base>=3.1
  #
  # # OWS
  # - owslib>=0.18.0
  # - pillow>=6.1.0
  # # Plotting
  # - gdal>=2.3.2
  # - scipy>=1.3.1
  # # Testing
  # - packaging>=20
  # - pytest
  # - pytest-mpl
  # - pytest-xdist
  # # Documentation
  # - beautifulsoup4
  # - pydata-sphinx-theme
  # - sphinx
  # - sphinx-gallery
  # # Extras
  # - flake8
  # - pykdtree
  # - requests
  # - setuptools_scm
  # - setuptools_scm_git_archive
  # - pip
  # - pip:
  #   - keplergl==0.3.2
  #   - matplotlib==3.4.3
  #   - msgpack==1.0.2
  #   - streamlit-autorefresh==0.0.1
  #   - streamlit-keplergl==0.1.0
  #   - movingpandas
