# To set up a development environment using conda, run:
#
#   conda env create -f environment.yml
#   conda activate geopy

# '''
# Environment created for the book "Geospatial analytics with Python"
# at LocatePress editorial
# It makes available the python libraries needed for the geospatial processing
# during the book's chapters.
#
# Author: Bryan R. Vallejo @BryanRVallejo
# '''
# Link: https://mybinder.org/v2/gh/bryanvallejo16/geopy-env/main
name: geopy
channels:
  - conda-forge
dependencies:
  - python==3.8
  - geopandas==0.11.0
  - shapely==1.7.1
  - osmnx==1.2.1
  - networkx==2.8.4
  - matplotlib==3.5.1
  - numpy==1.22.4
